version: '2'

services:
    web1:
        image: nginx:latest
        ports:
            - "80"
        volumes:
            - ./html:/var/www/html
            - ./nginx/tuan.conf:/etc/nginx/conf.d/default.conf
        links:
            - php:php


    php:
        image: php:5-fpm
        volumes:
            - ./html:/var/www/html


    web2:
        image: nginx:latest
        ports:
            - "80"
        volumes:
            - ./html:/var/www/html
            - ./nginx/tuan.conf:/etc/nginx/conf.d/default.conf
        links:
            - php:php


    web_loadbalancing:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./html:/var/www/html
            - ./nginx/lb.conf:/etc/nginx/conf.d/default.conf
        links:
            - php:php

